iot:
  server:
    hostname: 161.72.123.211
    port: 8088
    subscription_target: 'http://orm-viotserver:1026/v2/subscriptions'

  notification:
    required_headers: ["Destpage", "Apikey", "Userdata"]
    internal_name: '6_IOT_VAL'
    type: 'FieldsGroup'
    component: '3_GC_IOT_NombreComponente'
    magnitude: '3_GC_IOT_NombreMag'
    value: '3_GC_IOT_Valor'